# Generated by Django 4.1.3 on 2022-11-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='category',
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.ManyToManyField(to='documents.category'),
        ),
    ]
