# Generated by Django 4.1.3 on 2022-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='documents.category'),
        ),
    ]
