# Generated by Django 4.1.3 on 2022-11-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_file_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='category',
            new_name='categories',
        ),
    ]
