# Generated by Django 4.1.3 on 2022-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_rename_category_file_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
